name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
    - name: get src
      run: |
        git clone https://github.com/llvm/llvm-project.git -b release/17.x --depth 1
        cd llvm-project
        cmake -S llvm -B build -DLLVM_ENABLE_PROJECTS=clang -DLLVM_TARGETS_TO_BUILD=X86
    - name: Build solution
      working-directory: ./llvm-project
      run: |
        msbuild /p:Configuration=MiniSizeRel build/LLVM.sln

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        # Artifact name
        name: clang
        path: ./llvm-project/build

          
